// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.Picasso.subsystems;

import org.usfirst.frc0.Picasso.RobotMap;
import org.usfirst.frc0.Picasso.commands.*;
import com.ctre.CANTalon;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class winch extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX winchTalon = RobotMap.winchWinchTalon;
    private final WPI_TalonSRX winchTalon2 = RobotMap.winchWinchTalon2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void up() {
    RobotMap.winchWinchTalon.set(-0.4);
    RobotMap.winchWinchTalon2.set(-0.4);
    
    }
    public void off() {
        RobotMap.winchWinchTalon.set(0);
        RobotMap.winchWinchTalon2.set(0);
    }
    public void down() { 
    RobotMap.winchWinchTalon.set(-0.4);
    RobotMap.winchWinchTalon2.set(-0.4);
    }
    
}

